### ISSUE TITLE
Allow custom classNames for column and row cells 

### ISSUE THREAD

**Issue by akshayp** [glittershark/reactable#100]
It'd be awesome to support a `className` that can be passed into either rows or columns along with the label/content so users can get more granularity on a per cell basis for the `Td` and `Th` components when using `<Table>` directly

**Comment by glittershark** [comment]
This is doable using regular old react components - any HTML props you pass to the `<Tr>`, `<Td>`, `<Th>`, etc. are passed on to the rendered DOM node. So you can just do something like:

```jsx
var data = [
    {a: 1, b: 2, className: 'one'},
    {a: 3, b: 4, className: 'two'}
];

React.renderComponent(
    <Table>
        {data.map(function(row) {
            return (
                <Tr className={row.className}>
                    <Td column="a">{row.a}</Td>
                    <Td column="b">{row.b}</Td>
                </Tr>
            )
        })}
    </Table>,
    document.getElementById('my-table')
);
```
if you want to pass the className in your data object.

**Comment by rtsao** [comment]
It appears passing className to Tr doesn't work:
https://github.com/glittershark/reactable/pull/103

**Comment by akshayp** [comment]
Thanks @glittershark :+1:

**Comment by mikeygee** [comment]
@glittershark Your example here works if the columns are all known ahead of time. If the columns are generated from a varying data set, it gets a little messier generating the cells. It would be nice to be able to declare a class name within your data object, to be passed on to the cell.

Maybe something like this:
```javascript
var data = [
   { a: 1, b: { value: 2, className: 'abc' } }
]
```
If the data value is an object, then use the object's value property for the content, and add other properties as attributes on the td.
