### ISSUE TITLE
Incorrect documentation: reactable.common.js is no longer available, NPM package exists

### ISSUE THREAD

**Issue by appsciences** [glittershark/reactable#101]
In readme.md it states "If you'd rather use browserify or another CommonJS implementation to require() it, there's a file build/reactable.common.js in the repo or here if you'd like to download it directly." That file is no longer available (https://github.com/glittershark/reactable/raw/master/build/reactable.common.js).

Overall the documentation should be updated to reflect that NPM package is available.

**Comment by glittershark** [comment]
Oops! thanks for this, will update the docs asap

**Comment by appsciences** [comment]
Sure thing. Thanks much for creating this, great package, using it in several projects.
