### ISSUE TITLE
Customizing individual columns that are not in additional rows

### ISSUE THREAD

**Issue by appsciences** [glittershark/reactable#102]
It's quite common IMO to have selection or edit/delete controls as first column in a table. While there's a great way to customize columns in "additional" rows using Tr->Td..., I haven't found a way to insert  controls into columns that would trigger React events.

**Comment by glittershark** [comment]
Something like:
```jsx
var data = [{a: 1, b: 2}, {a: 3, b: 4}];

React.renderComponent(
    <Table>
        {data.map(function(row) {
            return (
                <Tr>
                    <Td column="a">{row.a}</Td>
                    <Td column="b">{row.b}</Td>
                    <Td column="delete">
                        <a onClick={function(ev) {
                            alert('do some XHR or something here');
                        }}>Delete</a>
                    </Td>
                </Tr>
            )
        })}
    </Table>,
    document.getElementById('my-table')
);
```
should work. Remember that this is all still React, and anything you can do with React you can do with Reactable

Feel free to reopen the issue if you run into any other issues :smile:

**Comment by nlaffey** [comment]
@glittershark Do you still feel this is a valid solution? It seems like your response is trying to do what this pull request is trying to enable: https://github.com/glittershark/reactable/pull/196
