### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by rtsao** [glittershark/reactable#104]
The package.json version and npm package should be updated due to the addition of the `filterBy` method.

**Comment by glittershark** [comment]
:+1:

**Comment by glittershark** [comment]
Done! Thanks for the issue :smile:

**Comment by rtsao** [comment]
Much thanks!

**Comment by rtsao** [comment]
Can you update the npm package again? Thanks!

**Comment by glittershark** [comment]
:+1: was waiting until I had some time to write docs for #112 - did that now. Thanks for the reminder.
