### ISSUE TITLE
Can't seem to get up/down arrows and the right cursor to appear on column headers for sorting.

### ISSUE THREAD

**Issue by appsciences** [glittershark/reactable#105]
Up/down arrows do not appear for me in column headers for sorting (as in http://glittershark.github.io/reactable/), and the hover cursor is an edit cursor. Am I missing a css file (couldn't find any)?

**Comment by glittershark** [comment]
That's all custom CSS - it doesn't ship with reactable as I'd rather let people style things themselves. The stylesheet for the table on your linked page is [here](

**Comment by glittershark** [comment]
Btw, the arrows are [here](https://github.com/glittershark/reactable/blob/gh-pages/stylesheets/table.css#L36) and [here](https://github.com/glittershark/reactable/blob/gh-pages/stylesheets/table.css#L43) :smile:

**Comment by appsciences** [comment]
Many thanks for clarification.

**Comment by Dashman99** [comment]
Hi @glittershark I am having troubles getting your css to work in my reactable.  I am using webpack and importing the `table.css` into my component .js file.  I have also tried importing it into my main `index.js` file which is my starting point for my react application.  BTW, I am a complete beginner to React.
