### ISSUE TITLE
props (e.g. className) aren't propagating (just npm package?)

### ISSUE THREAD

**Issue by EvanBurchard** [glittershark/reactable#106]
Hey @glittershark. Awesome work overall. I'm having a slight problem though getting my props to come through on my tr and td elements.  It seems like this is fixed with your latest changes.

I hate to be a pain, but if you get a chance, can you bump the version and push it to npm?

**Comment by glittershark** [comment]
I've just `npm publish`ed v0.9.5, including #103. Thanks!

**Comment by EvanBurchard** [comment]
Sweet.  Thanks for the quick response.  

(in case someone else ends up here, including me later) Still a no go for `<Td className>` but you can hack around it with the `<Tr className>` plus the `data-column` attributes on the `<Td>` if you need to style individual elements.

**Comment by glittershark** [comment]
Yeah, looks like I missed passing on props to `<Td>`s as well. That's #107 now

**Comment by glittershark** [comment]
Alright, just published v0.9.6, which fixes the issue with props not getting passed to Tds. Thanks!
