### ISSUE TITLE
Is it possible to pass in value for sorting when data is an array of objects?

### ISSUE THREAD

**Issue by cymen** [glittershark/reactable#113]
In the basic case where data is an array of objects, is it possible to pass in a value for sorting too? Or is there a way to pass in a function for formatting the value for display (and it is unformatted as value so it can still be sorted by that)?

I guessed one way might be to specify the value key for a given column in the columns array (ie use both `key`, `label` and `value`). That way, I could add another key to the object like say xyz_unformatted and point the value at that key. That doesn't work and maybe it shouldn't but it was the first way I guessed with the API.

**Comment by cymen** [comment]
I asked due to https://github.com/glittershark/reactable/pull/112.

**Comment by glittershark** [comment]
I've been waffling over this - on one hand, specifying values as objects with `key`, `label`, and `value` keys in the data array makes *sense*, but on the other hand it further complicates the already-complicated data array and props schema of the top-level `<Table>` object, and I'd like to gently prod users in the direction of drilling-down into the `<Tr>`s and `<Td>`s when they want to do more complex stuff like this.

I'm closing this issue for now, but feel free to fire back with more opinions / thoughts if you've got them.

**Comment by cymen** [comment]
@glittershark Okay, makes sense. I'm still wrapping my head around using the `<Tr>` and `<Td>` directly. It would be great to have an example of using them programmatically and I don't quite understand how it works if I have say 10,000 rows and want to page through them 20 at a time (I get the pagination but do I make 20 `<Tr>` and populate them with the first 20 records and then just keep swapping the records through?). Obviously, I need to try it some more so I'll do that. Thanks!

**Comment by glittershark** [comment]
Nope, Reactable will handle the pagination for you - just pass in all the possible Trs and it'll do all the magic for you.

**Comment by glittershark** [comment]
Feel free to keep commenting on this issue if you run into more stumbling blocks, since it'll help me write better documentation (which is definitely necessary, clearly)

**Comment by cymen** [comment]
So for 10,000 rows I pass in 10,000 Trs? Just to confirm -- I might be just thinking about things wrong if that is the case.

**Comment by glittershark** [comment]
Yep! That's how it's supposed to work.

**Comment by cymen** [comment]
It is making more sense now -- I made a basic demo to play with here:

https://github.com/cymen/reactable-demo

I noticed when I went from 10,000 rows to 50,000 rows, performance started to grind. What would it take to scale much higher (say 2M rows)? My direct usage of `reactable` is here:

https://github.com/cymen/reactable-demo/blob/master/table.js

**Comment by cymen** [comment]
I forgot to mention initial load is fast -- sorting is slow (doesn't seem to matter if string or numeric).

**Comment by cymen** [comment]
I made `CaseInsensitive` sort slightly faster with PR https://github.com/glittershark/reactable/pull/114. I'd like to add a `NumericInteger` sort too -- to avoid the overhead of parsing to float if one has a monster list. I'll do a PR for that too (happy to change the name of the sort).

**Comment by glittershark** [comment]
:+1: yay for optimization!

**Comment by glittershark** [comment]
In the future, I'd like to make the use case of *not* storing all the rows in memory supported - maybe a callback function that can return a Promise?
