### ISSUE TITLE
 Properties of <td> isn't attached correctly.

### ISSUE THREAD

**Issue by dimotsai** [glittershark/reactable#118]
In the section [Even More Customization](https://github.com/glittershark/reactable#even-more-customization), I found that the properties of `<td>` doesn't seems to be correct after rendering.

![2015-02-23 3 06 51](https://cloud.githubusercontent.com/assets/1947580/6319885/1b028e22-bb09-11e4-9e2a-7757c962b88a.png)

**Comment by thechrisproject** [comment]
This is what your rendered markup looks like? It is weird that you have capitalized <Tr> and <Td> elements rendered... those should be Reactable.Td and Reactable.Tr components, which render regular <tr> and <td> html elements. If you are using Reactable.Td, you shouldn't have to enter your own <td> elements. Also, if you are rendering a <td> inside a react component, it will only render the attributes that React supports, which are listed here:

http://facebook.github.io/react/docs/tags-and-attributes.html

**Comment by glittershark** [comment]
@thechrisproject if you look closer it looks like @dimotsai is using the [react dev tools][1], which display both the capitalized component names and the DOM nodes rendered by those components. So this is still a valid issue report :smile: thanks for taking a look at this though.

**Comment by glittershark** [comment]
This looks like a resurgence of #106 and #100. @dimotsai, can you verify you're using the latest Reactable version?

**Comment by thechrisproject** [comment]
@glittershark - Oops! Thanks for pointing that out. Color me embarrassed.

**Comment by dimotsai** [comment]
@glittershark, Yes, it is the latest version.

Looks like there is a problem in this for-loop (https://github.com/glittershark/reactable/blob/master/src/reactable.jsx#L253-L258).
```jsx
            // Attach any properties on the column to this Td object to allow things like custom event handlers
            for (var key in this.props.column) {
                if (key !== 'key' && key !== 'name') {
                    tdProps[key] = this.props.column[key];
                }
            }
```
Since `this.props.column` is always a string, this for-loop will take every character as a element and attach it to a `<td>`.

**Comment by glittershark** [comment]
ah, alright. thanks for narrowing that down. I've just pushed a commit that (I think) fixes the issue, can you try this out again on master and confirm that?

thanks!

**Comment by dimotsai** [comment]
It works. Thanks for your fix. :thumbsup:

**Comment by glittershark** [comment]
Cool! Just pushed version 0.10.1 with this fix.
