### ISSUE TITLE
Add <Reactable.Tfoot>, and ignore it when filtering or sorting.

### ISSUE THREAD

**Issue by gregeinfrank** [glittershark/reactable#131]
I think this is possible with a custom sort function, but is there an easier way to "anchor" the last row of the table so that when sorting, it's always the last row?

My use case is a table where the last row is an input box to add values, and should therefore always be at the end.

**Comment by glittershark** [comment]
Just stick it in a [`<tfoot>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tfoot)! :smile:

**Comment by glittershark** [comment]
...come to think of it, that might not work. It should, though

**Comment by glittershark** [comment]
Related to #123

**Comment by gregeinfrank** [comment]
@glittershark I just confirmed, that did not work.

**Comment by glittershark** [comment]
:+1: I'll get on implementing this, then.

**Comment by gregeinfrank** [comment]
awesome. You're the man!
