### ISSUE TITLE
Error in console: "Danger: Discarding unexpected node"

### ISSUE THREAD

**Issue by kopancek** [glittershark/reactable#133]
Hi,

I am getting an error in console when displaying reactable in my application. Using react 0.12.2 and reactable 0.10.1.

```
Danger: Discarding unexpected node: 
<span data-reactid=".0.1.1.0.2:$tabContents.$Interface.$table.$thead.0"></span>
...
```

I've narrowed it down to the filterer and the source code in reactable.jsx:
```
{this.props.filtering === true ?
                        <Filterer
                            colSpan={this.props.columns.length}
                            onFilter={this.props.onFilter}
                            placeholder={this.props.filterPlaceholder}
                            value={this.props.currentFilter}
                        /> : ''}
```
The problematic part is returning an empty string there, which creates the unexpected node. In my opinion way cleaner code would look like:
```
{if (this.props.filtering === true) { 
                        return <Filterer
                            colSpan={this.props.columns.length}
                            onFilter={this.props.onFilter}
                            placeholder={this.props.filterPlaceholder}
                            value={this.props.currentFilter}
                        />
}}
```
Because it does not output an empty element if the filterering is disabled. So it would also stop react from complaining.

**Comment by coryasato** [comment]
I get a similar error when I'm bringing the component in as a conditional under render.

```Danger: Discarding unexpected node: <span data-reactid=​".0.1.1.0.0.1.0.0.0:​1.2.0.$thead.0">​</span>​```

When I setState and re-render my view via a flux store, I get the error.  On initial load I have the Table rendered with no error, so it's somewhere in the clean-up perhaps?

I'll try to dig further tmrw but kopancek's solution did not resolve my error nor am I using the filtering prop.

**Comment by andybeesee** [comment]
Same thing happened to me, the initial render was fine but I would get ```Danger: Discarding unexpected node:...``` when I would attempt to sort the data (not even using a custom sort).

I had a customized table with cells like...

```
	<Td column='whateverObject'>
		<SomeComponent object={Object} />
	</Td>
	<Td column='anotherObject'>
		{ anotherObject.name }
	</Td>
```

Where the render method of *SomeComponent* looked a little like...

```
	render: function(){
		if(typeof(obj.someProperty) === 'undefined'){
			return (<p>error message</p>);
		}

		return (
			<div>
				{ obj.value}
			</div>
		)
	}
```

Switching the component to always return a div stopped the error for me.

```
	render: function(){
		if(typeof(obj.someProperty) === 'undefined'){
			return (<div>error message</div>);
		}

		return (
			<div>
				{ obj.value}
			</div>
		)
	}
```

I don't know what I was thinking returning that ```<p>``` in there.

**Comment by glittershark** [comment]
I think this is a couple errors, all related to the rules the DOM places on nesting specific nodes:

- you can't have anything in a `<tr>` except a `<td>` or a `<th>` - this is why the `<Filterer>` is complaining
- You can't have a `<p>` inside another `<p>` - this seems like @andybeesee's error

The latter is all calling code, but the former is definitely a Reactable bug.

**Comment by benkeen** [comment]
+1 Ran into this too.

**Comment by buduguru** [comment]
The same here. I had
```
<p dangerouslySetInnerHTML={{__html: marked(this.data.article.fulltext.toString())}} />
```
error disappeared after I changed `p` to `div`

**Comment by glittershark** [comment]
@buduguru Is your `<p>` nested inside another `<p>`?

**Comment by buduguru** [comment]
@glittershark no, it is was inside `<div>`
