### ISSUE TITLE
If table doesn't render during a given pass, it will not render on any subsequent passes

### ISSUE THREAD

**Issue by paulmelnikow** [glittershark/reactable#141]
Hi there, thanks for this great library!

I have a component which loads data from a web service and then displays in a table. Until the data is loaded, I want to display nothing. I have code like this, which works fine:

```js
render: function () {
    if (! this.state.testSetData) return null;
    return <table>...</table>;
 }
```

When I try to do the same with reactable I run into trouble. It seems that if `<Table>` doesn't render on a given pass, it will not render on any subsequent pass either.

Here's an example:

```js
var Testcase1 = React.createClass({

    getInitialState: function () {
        return { show: false };
    },

    componentDidMount: function () {
        var component = this;
        setTimeout(function () {
            component.setState({ show: true });
        });
    },

    render: function () {
        if (! this.state.show) return null;

        var data = [
            { Name: 'Griffin Smith', Age: 18 },
            { Age: 23,  Name: 'Lee Salminen' },
            { Age: 28, Position: 'Developer' },
        ];

        return React.createElement(
            Table,
            { className: "table", data: data }
        );
    },
});
```

Expected behavior is that the table appears, because setTimeout changes show to true so it should render. Observed is that setTimeout runs but the table doesn't appear. Set `show: true` in getInitialState, and this works fine. Change `show` from true to false to true and the table initially appears, then hides, but never comes back.

For comparison, here is some code that works as expected:

```js
var Foo2 = React.createClass({

    getInitialState: function () {
        return { show: false };
    },

    componentDidMount: function () {
        var component = this;
        setTimeout(function () {
            component.setState({ show: true });
        });
    },

    render: function () {
        if (! this.state.show) return null;

        return React.createElement(
            'div',
            null,
            'hello'
        );
    },
});
```

Wonder if this might be related to #59, but not sure.

This is in reactable 0.10.1, react 0.12.2.

**Comment by glittershark** [comment]
Might want to change your render to:
```jsx
return <div>{this.state.show ? <Reactable.Table>...</Reactable.Table> : null}</div>;
```

React doesn't generally like `render` methods that return anything other than a valid React component.

Feel free to reopen the issue if you're still experiencing problems
