### ISSUE TITLE
error: filterBy is not a function

### ISSUE THREAD

**Issue by MikaelLarsson** [glittershark/reactable#143]
I don't see any issues on this so it's probably just me so I apologize in forehand. I get "filterBy is not a function" error.

This is my render method:

```javascript
var table = <Table className="small" data={ items } itemsPerPage={ 4 } sortable={ true } filterable={ ['Leverantör'] } />;

return (
   <div id="resultList">
        { table.filterBy( query ) }
        { table }
    </div>
);
```

**Comment by glittershark** [comment]
Rather than storing the return value of `<Table>` and referencing that, in your case you need to use a React [ref][], on the `<Table>`, and reference that.

[ref]: https://facebook.github.io/react/docs/more-about-refs.html

**Comment by MikaelLarsson** [comment]
I'm sorry but I can't wrap my head around this. I get the same error as before. When i console `this.refs.itemsTable` I see that the first time it will be `undefined`. Then it will render two more times with reference to the table.

This is my render:

```javascript
this.refs.itemsTable.filterBy( query );
return (
    <div id="resultList">
        <Table ref="itemsTable" className="small" data={ items } itemsPerPage={ 5 } sortable={ true } filterable={ ['Leverantör'] } />
    </div>
);
```
