### ISSUE TITLE
unsafe string for a column label

### ISSUE THREAD

**Issue by JbRezidu** [glittershark/reactable#144]
Hi,

I actually use reactable for my project, but i have a little problem, when I want to use the unsafe string for a column label. Indeed I have an error : "unexpected string" on the line when i use the unsafe string for a column label. I am not english so, I don't know if I well understand the Readme  about that...

This is my code : 

	var Table = Reactable.Table,	
		unsafe = Reactable.unsafe;

	var Test=React.createClass({
		render:function(){
			return(
				
				<Reactable.Table className="table" id="table" data={[
				    {unsafe("Name<br/>test"): unsafe('Lee Salminen'), Age: 23, Position: unsafe('<b>test</b>')},
				    { unsafe("Name<br/>test"): 'Griffin Smith', Age: 18, Position: 'Engineer'},
				    { unsafe("Name<br/>test"): 'Ian Zhang', Age: 28, Position: 'Developer'}
				]}
				sortable={true}
				defaultSort={{column: 'Age', direction: 'asc'}}/>
							
			);
		}
	});

	React.render(
	    <Test/>,
	    document.getElementById('app')
	);

**Comment by JbRezidu** [comment]
Sorry for this post, I found it alone.

**Comment by akohout** [comment]
It's always nicer to post the found solution..
