### ISSUE TITLE
Getting an error using test.html

### ISSUE THREAD

**Issue by 02ps719** [glittershark/reactable#168]
Hi,

Thanks for this nice component. 

I am trying to use this React Table for a project and to get a hang of it, downloaded the zip file https://github.com/glittershark/reactable/archive/master.zip and tried opening up test.html in chrome. 

Ensured I changed the reference to React to 0.12 in the test.html source file. 

But I am getting this error - 'Super expression must either be null or a function, not undefined'

Is there anything else I need to do to get this up and running? Because getting this right would allow me to use this component. 

Thanks,
V
![reactable-setuperror](https://cloud.githubusercontent.com/assets/2115004/9271914/377a2528-429b-11e5-8ae5-4b3d0910defb.PNG)

**Comment by glittershark** [comment]
`test.html` is pretty out of date - there's no guarantee that it'll work. I should just get rid of it.
