### ISSUE TITLE
Pass cell/row classes through object?

### ISSUE THREAD

**Issue by Anahkiasen** [glittershark/reactable#169]
Currently to assign a class to a cell you have to override Reactable's whole structure, it would be nice if you were able to do something like:

```js
const data = [
  {
    Name: 'Foobar',
    Balance: {className: 'danger', value: 0},
  }
];
```

Could also work for all other attributes, by then doing internally something like `<Td {...attributes}>{attributes.value}</Td>` or something

**Comment by glittershark** [comment]
This is beyond the scope of what I want to do with Reactable. It'd be pretty easy to do in a wrapper class if you like, though.
