### ISSUE TITLE
New pagination

### ISSUE THREAD

**Issue by cumbreras** [glittershark/reactable#174]
Hi,

As discussed in other issue, I think it's a really needed the re-implementation of the pagination feature, improving the logic to display the page links in a smarter way. 

I suggest something more in google style (hiding most of the actual page links) adding more, last, previous and first?

Examples and ideas more than welcome!

**Comment by tsargent** [comment]
I think this is a great idea.  I have a small PR going here that might be a step in that direction: https://github.com/glittershark/reactable/pull/175

**Comment by cumbreras** [comment]
Brilliant work @tsargent !
