### ISSUE TITLE
validateDOMNesting warning w/ React 0.14

### ISSUE THREAD

**Issue by rchanou** [glittershark/reactable#177]
I'm using React 0.14 beta 3. Rendering any Table triggers this warning:

```
Warning: validateDOMNesting(...): <span> cannot appear as a child of <thead>. See App > Table > Thead > thead > span.
```

Additional prop changes after this can cause Invariant Violation errors and break the app.

**Comment by glittershark** [comment]
Looks similar to #133. Are you using the latest version of Reactable?

**Comment by glittershark** [comment]
Oops, scratch that. Looks like a similar but not identical issue.

**Comment by rchanou** [comment]
Upgraded to version 0.12.0 for `reactable`, and 0.14.3 for `react`/`react-dom` and haven't noticed any errors, so closing this. Thanks.
