### ISSUE TITLE
Add support for parsing column labels out of a Th

### ISSUE THREAD

**Issue by reggi** [glittershark/reactable#182]
I'm trying to recreate this functionalty: 

![screen shot 2015-09-16 at 5 07 28 am](https://cloud.githubusercontent.com/assets/296798/9901192/ea16af60-5c33-11e5-8357-81e03681d2cb.png)

The first column is a react component and the third has a special sorted class.

Can this be achieved with this module? I check the docs and I didn't see a way this was possible.

**Comment by glittershark** [comment]
So, currently a workaround is to set the `label` property of the column to a `reactable.Unsafe` string. That's definitely less than optimal, so we should add support for parsing column labels out of a `Th`

**Comment by glittershark** [comment]
@reggi just pushed [0.11.2][tag] containing an implementation for this. The corresponding docs can be found [here][docs] (see the second bullet point and associated code example)

[tag]: https://github.com/glittershark/reactable/releases/tag/0.11.2
[docs]: https://github.com/glittershark/reactable#customizing-columns

**Comment by reggi** [comment]
Hey just tried to use this and found a bug, put in a pull request to fix it.

Just wanted to mention that in your example the `content` will not show, It would be nice if it still showed no? Just a thought, I don't mind.

```js
<Table className='table-hover expanded'>
  <Thead>
    <Th column='name'>
      <strong className='name-header'>First Name, Last Name</strong>
    </Th>
  </Thead>
  <Tr className='special-row' data={{ name: 'Other Row', content: 'This is a different row' }}/>
</Table>
```

**Comment by glittershark** [comment]
The idea is that like with specifying an explicit `columns` arrwy
