### ISSUE TITLE
Can't set the className of a Th

### ISSUE THREAD

**Issue by reggi** [glittershark/reactable#189]
Not sure why but it's really frustrating :(

**Comment by glittershark** [comment]
className of what? the Th?

**Comment by reggi** [comment]
@glittershark Yeah I'm unable to set the `className` of the `Th`. Thoughts on why? The props filter shouldn't be stripping it.

**Comment by glittershark** [comment]
Yep, I know exactly why this is happening.

**Comment by reggi** [comment]
Seems like your applying your own `className` like this `reactable-th-{this.props.column}` can't find where though. Perhaps should be adding passed in className instead of overriding?

**Comment by reggi** [comment]
Here? https://github.com/glittershark/reactable/blob/2987bf1659b43aa171703f80e8586a1664a8069c/src/reactable/thead.jsx#L60

**Comment by glittershark** [comment]
We're not actually storing the passed in `Th`, we're just parsing the `column` and `children` out of it and storing it in an array ([here][store]), and then re-building it into a `Th` [here][rebuild].

Solution in my mind would be to store a `headerProps` attribute along with that that's the result of calling `filterPropsFrom` on the `Th`'s props

[store]: https://github.com/glittershark/reactable/blob/master/src/reactable/thead.jsx#L14-L17
[rebuild]: https://github.com/glittershark/reactable/blob/master/src/reactable/thead.jsx#L60-L66

**Comment by reggi** [comment]
Can't we just store all the props from `th.props` instead of just `column` and `children` and rebuild the whole thing? That way I we can pass it whatever we want?

**Comment by glittershark** [comment]
I'd like to keep the props that are only necessary for rebuilding a component separate from the props that reference the actual data. In that vein, I feel like the best bet is:

```jsx
{
  column: 'name',
  props: {
    className: 'foobar',
    children: <my component>,
    ...
  }
}
```

**Comment by glittershark** [comment]
Actually, on second thought that's not as good because we still want to maintain backwards compatibility with [the columns array Table prop](https://github.com/glittershark/reactable#customizing-columns), and so we need to keep the `label` prop around, and it makes sense to reuse that for children. So, final word is `column`, `headerProps`, `label`

**Comment by reggi** [comment]
So your proposing this: `<Th headerProps={className: 'something'}>` ?

**Comment by glittershark** [comment]
nonono, I'm just talking about the intermediate internal representation. The caller API would still use regular old props

**Comment by reggi** [comment]
Gotcha, I just put this together super sloppy. [Full example here](https://gist.github.com/reggi/f3ceef54843aa6d0ba14)

```js
columns.push({
  key: th.props.column,
  label: th.props.children,
  props: function () {
    var copy = Object.assign({}, th.props);
    delete copy.column;
    delete copy.children;
    return copy;
  }(),
}

<Th className={thClass}
  key={index}
  onClick={this.handleClickTh.bind(this, column)}
  role="button"
  tabindex="0"
  {...column.props}>
  {column.label}
</Th>
```

**Comment by glittershark** [comment]
oops, crossed the streams :smile: 2b97c13 includes concatenating together classes, though

**Comment by mephux** [comment]
@glittershark this still seems to be an issue.Maybe this was solved in another way? @reggi how did you eventually workaround this?

**Comment by reggi** [comment]
@mephux I ended up rolling my own table :/
