### ISSUE TITLE
Cannot resolve module 'react-dom'

### ISSUE THREAD

**Issue by MikaelLarsson** [glittershark/reactable#206]
After upgrading to 0.12.0 I get this from grunt:

ERROR in ./~/reactable/lib/reactable/filterer.js
Module not found: Error: Cannot resolve module 'react-dom' in f:\path\node_modules\reactable\lib\reactable
 @ ./~/reactable/lib/reactable/filterer.js 23:16-36

What is this react-dom? Can't find it in the dependencies. Using React 0.13.3.

Any ideas?

**Comment by jasonblanchard** [comment]
`react-dom` was introduced in React `0.14`, so I *think* that means you have to upgrade to React `0.14` to be compatible with that version of Reactable.

**Comment by MikaelLarsson** [comment]
I will try. It states in the package.json that reactable is compatible with 0.13.3. Will investigate.

**Comment by glittershark** [comment]
Yeah, as of version 0.12.x Reactable only supports 0.14 or higher. I'll add a note about that to the README
