### ISSUE TITLE
Render a ReactComponent

### ISSUE THREAD

**Issue by Gouthamve** [glittershark/reactable#207]
I don't know if this is a good practice, but I would like to render a react component in a column. While I am using unsafe, it doesn't seem to work.

Is there any way I can get this to work?

**Comment by glittershark** [comment]
```jsx
<Reactable.Table>
  <Reactable.Tr>
    <Reactable.Td><MyReactComponent /></Reactable.Td>
  </Reactable.Tr>
</Reactable.Table>
```

**Comment by glittershark** [comment]
see [these docs](https://github.com/glittershark/reactable#even-more-customization)

**Comment by Gouthamve** [comment]
Thanks! It works!
