### ISSUE TITLE
Version bump?

### ISSUE THREAD

**Issue by jasonblanchard** [glittershark/reactable#210]
Can we get a version bump? Waiting on some sweet, sweet, `noDataText` ;)

If you're on a particular release schedule, that's totally cool, just trying to plan ahead.

Thanks!

**Comment by danlopez191** [comment]
:+1:

**Comment by jasonblanchard** [comment]
Looks like master is on `0.12.1` but the npm release is still only at `0.12.0` https://www.npmjs.com/package/reactable

Can we can a version bump on npm?

Thanks!

**Comment by glittershark** [comment]
that's weird, Travis is supposed to be pushing to npm for me. Credentials might be out of date.

**Comment by jasonblanchard** [comment]
Any updates on this?

**Comment by glittershark** [comment]
Next build should push a version to npm
