### ISSUE TITLE
Does not work with seamless-immutable / redux-crud

### ISSUE THREAD

**Issue by hampusohlsson** [glittershark/reactable#220]
Passing in a [seamless-immutable](https://github.com/rtfeldman/seamless-immutable) data array (in my case from [redux-form](https://github.com/erikras/redux-form)) generates a `Maximum call stack size exceeded` error. 

Right now my fix is to make the data mutable using `.asMutable()`

**Comment by glittershark** [comment]
Good that there's a temporary workaround at least, but from what I can read about that library it seems like it's probably a bug with it

**Comment by hampusohlsson** [comment]
Yeah, that might be the case.. And actually I was wrong, the library using it is (redux-crud)[https://github.com/Versent/redux-crud] which is much less popular than redux-form, so it might not be that big of an issue.

**Comment by hampusohlsson** [comment]
Seems like this issue is [being addressed already](https://github.com/rtfeldman/seamless-immutable/issues/73) in seamless-immutable

**Comment by glittershark** [comment]
Sweet! Gonna close this then, feel free to reopen if it does in fact turn out that Reactable is doing something wrong
