### ISSUE TITLE
Drag & droppable columns?

### ISSUE THREAD

**Issue by raptoria** [glittershark/reactable#224]
Is this a feature that you might be considering adding?

Thanks!!

**Comment by glittershark** [comment]
Almost definitely not, given the "simple" tagline. I would, however, be open to exposing whatever API would be necessary for another library to implement that functionality.

**Comment by raptoria** [comment]
If you could expose the existing API that would be awesome!

thanks!!

**Comment by glittershark** [comment]
I'm not sure what you mean

**Comment by raptoria** [comment]
oh.. I was just going off of your last statement - I would, however, be open to exposing whatever API would be necessary for another library to implement that functionality.

I will try to implement it myself, if possible.
