### ISSUE TITLE
Feature Conversation - Canceling Outer Sort Event

### ISSUE THREAD

**Issue by JonathanBruce** [glittershark/reactable#231]
Working on a nested sorting component of sorts. 

IE a sort with its own ascending and descening within the ascending descending column sort
<img width="439" alt="screen shot 2016-01-08 at 4 46 38 pm" src="https://cloud.githubusercontent.com/assets/1743411/12210392/9591f226-b627-11e5-801f-c85368f7e58f.png">

I was able to accomplish the sorting using the sortFunction easily. 

Though the click event goes through the Table sort before the child component sort so I can't cancel or stop propagation of the event to the parent component. 

How would you see a path to work through an issue like this where users might want to have more detailed sorts or potentially canceling a sort inside a column header. 

Maybe use a promise that gets passed up through the this.props.onsort that on resolve actually fires `this.sortByCurrentSort()`?

**Comment by glittershark** [comment]
would returning false from onsort work for you?

**Comment by JonathanBruce** [comment]
I'm not sure what that would do?

**Comment by glittershark** [comment]
cancel the sort, I guess. Maybe I'm not understanding your problem.

**Comment by JonathanBruce** [comment]
I'll reword it 

there's a component 

```
<Thead ....>
    <Th column='MyColumn'>
         Name
         <div>
             // checkmark component to enable second sort criteria
             // up and down arrow to indicate asc/desc
         <div>
        // name up and down arrow to indicate asc/desc
   </Th>
   // other columns
</Thead>
```

If the checkmark is enabled the sort function goes from `alphabetic` sort to `sort by (if selected or not flag) then by alphabetic`

Now both the alphabetic sort and the selected sort have their own direction, IE We might want to sort ascending alphabetically (the outer arrow) and descending by the inner criteria. 

So we can change the outer sort by clicking anywhere in the TH, that's our normal onSort that will flip asc desc. And this extra `selection sort` component with its own asc/desc if you click inside you can do the same flip, but this should only flip the inner arrow and the inner direction asc/desc. 

I assumed it would have an event on the child that I could stop from bubbling up to the parent TH element. But the TH OnSort event handling method fires before the child's OnClick event.

**Comment by JonathanBruce** [comment]
any thoughts?

**Comment by glittershark** [comment]
that's weird; sorting should be based on a click event. Definitely sounds like a bug to me. I'll accept a patch to make the events fire in the right order.

**Comment by JonathanBruce** [comment]
I closed it because after further examination it was my own fault, the event was being propagated from the parent event handler of the button that I thought was firing the event. So it does work as intended, such that, if you handle the event and stop propagation on the child container inside a `Th` element it won't bubble up to trigger OnSort.

**Comment by glittershark** [comment]
oh, nice.
