### ISSUE TITLE
sort by and display different values

### ISSUE THREAD

**Issue by seiyria** [glittershark/reactable#232]
Suppose I have a column that gets formatted a special way, I represent the value like this:

```
{ value: 105,
  string: '1s 5c' }
```

I want to display the string, but I want to sort by the value. It seems I can sort by the value, but I'm unsure how to display the string. When put in the column, it just comes up as [Object object], and I can't seem to find any documentation that lets me write a formatter for the table data in addition to the already-existing sorting.

**Comment by glittershark** [comment]
per the documentation, you can specify a `value` attribute to your `Td` and render the contents just like any other react element

**Comment by seiyria** [comment]
What I'm suggesting is that I have a label and key already. I have two keys - one that is the display value and one that is the sort value. The documentation does not appear to address this case.

Suppose my object looks like this:

```
{ name: 'Some Weapon',
  cost: { string: '1s 5c', value: 105 } }
```

I want to display two columns: "Name" and "Cost"

When I display cost, I want to display `cost.string`. When I sort by cost, I want to sort by `cost.value`. That does not appear to be possible.

**Comment by glittershark** [comment]
`<Td value={cost.value}>{cost.string}</Td>`

**Comment by seiyria** [comment]
Ah, so you can do it with the expanded syntax. Is there any chance this can be expanded to just have a `display` function you can pass in for the columns? It seems wasteful to have to expand the table just to do this.

Right now, I have this:

```
<Table className="results"
               data={data}
               itemsPerPage={25}
               pageButtonLimit={10}
               sortable={sorts}
               filterable={['name']}
               columns={tableColumns}
               defaultSort={{ column: 'cost', direction: 'desc' }}
               noDataText="No items meet this criteria." />
```

where `tableColumns` looks like this:

```
const tableColumns = [
      { label: '', key: 'iconUnsafe' },
      { label: 'Name', key: 'name' },
      { label: 'Type', key: 'type' },
      { label: 'Cost', key: 'cost' },
      { label: 'Chat Link', key: 'chat_link' }
    ];
```

I'd like to add the `display` function to my `tableColumns` object because I can do pretty much everything else in my configuration.

**Comment by glittershark** [comment]
This has been asked before, and no, I'd like to avoid adding any more options to the top-level Table object, especially for things that are already possible with nested components. The latter approach (`<Td>`s inside `<Tr>`s inside a `<Table>`) should be considered the *default*, with the options available for the top-level table object being a shortcut when you're not doing anything particularly complex

**Comment by seiyria** [comment]
I can't say I consider this to be complex, but as long as it's possible, I suppose that's fine. I actually ended up just writing a function that reverses my `cost` format into a number so this isn't really super relevant to me anymore.

**Comment by phillyo2** [comment]
Is there a way to over write just one column?  So we still pass a data attribute to the Table 
<Table data={aListOfObejcts}/> but add the value attribute just to one of the columns so we can sort that column by the value rather than the data?
