### ISSUE TITLE
Add ability to set the current page via a prop passed to the table

### ISSUE THREAD

**Issue by dcurletti** [glittershark/reactable#234]
Is it possible to change what the current page of the table is when toggling to a different sort method?  Example: I'm on page 5 and I would like to sort by name alphabetically.  When I click the column header to sort, I would like the table to go to page 1 so that the first row is showing a name that starts with the letter 'a' (assuming there is an individual with the name that starts with the letter).

**Comment by castrolem** [comment]
+1

**Comment by glittershark** [comment]
there's an `onSort` event prop, so all this really needs is a way to change the current page via a prop passed to the table

**Comment by damienleroux** [comment]
+1. When reloading data for the table. It keeps the current visited page as default. I need it to come back to 0
