### ISSUE TITLE
please help with osrt function

### ISSUE THREAD

**Issue by yocmen** [glittershark/reactable#239]
i have this function:

sortFunction: function(a, b){
				    	if(a > 0)
        					a = parseInt(a);

        				if(b > 0)
        					b = parseInt(b);

				    	return a >= b ? 1 : -1;
}

how can i made the function generic to use it in several columns???

like sortFunction: this.mySortFunc()

if i add a, b there are not defined and without the params dont work, how can i make it to work? please help.

**Comment by glittershark** [comment]
This seems like more of a question for something like StackOverflow
