### ISSUE TITLE
Which addons are required?

### ISSUE THREAD

**Issue by blandflakes** [glittershark/reactable#249]
The docs say that this depends on react 12.0, with addons. I don't want to blindly install all addons - which addons does this library depend on from the list [here?](http://facebook.github.io/react/docs/addons.html)

**Comment by nrankin** [comment]
I really like to know this too...my team aren't keen to add them all in.

**Comment by glittershark** [comment]
Looks like the docs on that point are actually out of date - looking at that list I don't see anything that we're using. If memory serves me, the addon that we required was the children helper, but I guess that's built into react-core now.
