### ISSUE TITLE
Add css class to filter input

### ISSUE THREAD

**Issue by shinnyx** [glittershark/reactable#259]
I was expecting something like `filterClassName` but it is not implemented. In the end I injected a class: 
> $('.reactable-filter-input').addClass('form-control');

which is ugly and not reliable.

May i know if there's any better ways to achieve this? I'm new to react so do let me know if there's a better alternative. Otherwise are you good with a PR on implementing a `filterClassName`?

**Comment by glittershark** [comment]
I'd accept a patch for `filterClassName`.
