### ISSUE TITLE
Header row is also moving with scroll

### ISSUE THREAD

**Issue by kaushik143** [glittershark/reactable#273]
Implementing table using reactable but the I am not able to control the header position while scrolling the content of table. Is there any way by which I can  implement this using reactable.

**Comment by glittershark** [comment]
throw a `position: fixed;` on it, probably.
also, I would recommend asking this on StackOverflow

**Comment by RyanThomasMusser** [comment]
@kaushik143 did you ever find a workable solution to fixing the header? Would like to see what you concluded with before I dive in, thanks mate~

**Comment by PhilNorfleet** [comment]
I am still struggling to solve this, seems like there should be a <Tbody> component that you can set the height and make scrollable and keep the header fixed like normal.

**Comment by stclairdaniel** [comment]
I'm also curious about a solution. Using `position: fixed`breaks the column layout, unfortunately.

**Comment by Praki06** [comment]
Did anyone find a workable solution for this issue?

**Comment by kalimuthu123** [comment]
this css works partially in the reactable table
table thead tr:nth-child(1) th{
   background: white;
   position: sticky;
   top: 0;
   z-index: 10;
 }
