### ISSUE TITLE
Unable to Use Custom Headers

### ISSUE THREAD

**Issue by jflayhart** [glittershark/reactable#275]
I think I saw this as a closed issue, but this is still not working for me... See my gist: https://gist.github.com/jflayhart/5d049a5da4d9cc26e67eecdf5c05a6ec#file-reactable-L15

You will see I am needing to use the actual column label as the column prop, so that I can get it formatted the way I need to, but then that means I can't create custom header, which I need... If I do it the way your docs say, then it simply defaults to using the column keys as the name for each column and there is no way I can create any sort of custom headers like your docs day I can... am I missing something here?

**Comment by glittershark** [comment]
What do you mean by "name for each column" in "using the column keys as the name for each column"?

**Comment by jflayhart** [comment]
I mean the columns become named automatically by the column key and overwrite any custom headers I try to set... For example, your docs say https://github.com/glittershark/reactable#customizing-columns, but when I follow that approach, it just uses "name" as the column name, instead of First Name, Last Name.

**Comment by glittershark** [comment]
Can you send a code example of something that's breaking? Even better, a breaking test case?

**Comment by jflayhart** [comment]
I mean, I sent you a code example in my gist :) What's going on there though is I bring in column object as a prop composed as `column = {key: "fname", label: "First Name"}`, so what used to work was when I used `column.key` it would use "First Name" with my `get tableHeader ()` function (line 27 of my gitst). But now if I use column.key in line 15, it will use "fname" as the column name... I have left comments in the code saying where things aren't working. I can try working on a test case, but figured my explanation would be enough and not sure when I will have time to run unit tests on your code.

**Comment by jflayhart** [comment]
Ahh! I forgot to return the code block in my getHeader() function... sorry. I honestly couldn't figure out what was wrong. Closing >.<
