### ISSUE TITLE
Events for pagination / filtering

### ISSUE THREAD

**Issue by leesalminen** [glittershark/reactable#28]
I  need an event I can handle for pagination / filtering so that I can trigger a function when those fire.

**Comment by thechrisproject** [comment]
This would be a fantastic feature to add and would save me a lot of hacky work.

**Comment by thechrisproject** [comment]
Looking at the latest docs, I see there are onFilter, onSort, and onPageChange props. Perhaps this issue should be closed? @glittershark ?

**Comment by glittershark** [comment]
yeah, actually, good call. Thanks @thechrisproject
