### ISSUE TITLE
Table without a Thead

### ISSUE THREAD

**Issue by cklab** [glittershark/reactable#284]
I'd like to be able to create a `Table` that doesn't have a heading and I haven't been able to figure out a way to do it in version 0.13.2. Does this feature exist somehow and I've missed it?

If this feature is within scope and does not exist, I'd like to make a pull request with the following change: 

- add prop `hideTableHeader` to `Table`, similar to `hideFilterInput`.

Thoughts?

**Comment by glittershark** [comment]
yeah, that'd be fine for me, though I'm curious about your specific use case

**Comment by cklab** [comment]
In my case, it's mainly to format a name/value pair with table-like behavior; like a transposed table where the rows serve as the labels and the columns have the potential to grow. 

Besides that, the [HTML standard](https://html.spec.whatwg.org/multipage/tables.html#tables) says a thead is optional so, I figure, why the hell not :)
