### ISSUE TITLE
React v15 complains about props being passed to native <table> element

### ISSUE THREAD

**Issue by dcurletti** [glittershark/reactable#291]
As soon as I upgraded to React v15 I started getting this error: 
<img width="1466" alt="clients___realscout" src="https://cloud.githubusercontent.com/assets/7329041/16541772/b465ffa4-4041-11e6-9095-130ffcbcad51.png">

Which I can only assume is because of this line: 
https://github.com/glittershark/reactable/blob/6da047162b8bfe37dde79ebe91190d974ccb79c5/src/reactable/table.jsx#L503

**Comment by vdh** [comment]
This was a new warning added in v15.2 if I'm not mistaken.

**Comment by nic** [comment]
This is new at v15.2:
3 days ago: https://gist.github.com/jimfb/d99e0678e9da715ccf6454961ef04d1b

**Comment by dcurletti** [comment]
Yea, I should have been more explicit in my initial post: I think it is a bit risky to pass the `rest` of the props to the native table element, especially only being filtered by a small blacklist.  I think a whitelist would be more appropriate, taken from here: http://www.w3schools.com/tags/tag_table.asp .  The table doesn't even have that many unique attributes.

**Comment by vdh** [comment]
@dcurletti The blacklist in `filterPropsFrom ` is recycled between all the other tags as well, so to replace it with a whitelist you'd probably need to create different whitelists per tag.

I took a shot at expanding the blacklist with as many props as I could find in #293

**Comment by hassankhan** [comment]
Just for everyone's attention, still getting the same errors with React v15.3, too

**Comment by vdh** [comment]
@hassankhan Are you using `master`? Because the fix hasn't been put into a release yet.

**Comment by hassankhan** [comment]
Yep, I noticed that so I opened #305 😄

**Comment by dcurletti** [comment]
Gracias.
