### ISSUE TITLE
warning.js:44 Warning: Unknown props

### ISSUE THREAD

**Issue by doljura** [glittershark/reactable#299]
Hi! I'm trying to use your lib first time. This is my code:
...

        `return (
           <div>
                <Table className="table market-table" id="table" data={[
                    { market: 'Lala1', sell: 1111, buy: 1111},
                    { market: 'Lala2', sell: 2222, buy: 2222},
                    { market: 'Lala3', sell: 3333, buy: 3333}
                ]}>
                    <Thead>
                        <Th column='market'>
                            <span>Market</span>
                        </Th>
                        <Th column='sell'>
                            <span>Sell</span>
                        </Th>
                        <Th column='buy'>
                            <span>Buy</span>
                        </Th>
                    </Thead>
                </Table>
            </div>
        )
    }`

Table works but i have next warnings:

warning.js:44 Warning: Unknown props `defaultSortDescending`, `filterBy`, `hideFilterInput` on <table> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in table
    in Table
    in div
    in exports
    in div
    in exports
    in div
    in div
    in div
    
warning.js:44 Warning: Unknown props `filtering`, `onFilter`, `filterPlaceholder`, `currentFilter`, `sort`, `sortableColumns`, `onSort` on <thead> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in thead
    in Thead
    in table
    in Table
    in div
    in exports
    in div
    in exports
    in div
    in div
    in div
    in exports

I don't know how to avoid those warnings from my side.

**Comment by glittershark** [comment]
See #293
