### ISSUE TITLE
Warning: Unknown prop `props` on <td> tag.

### ISSUE THREAD

**Issue by hassankhan** [glittershark/reactable#311]
Seems like perhaps a few elements got missed?

**Comment by Daniel-Baranowski-BJSS** [comment]
I got the same problem. 
`Warning: Unknown prop `props` on <td> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in td (created by Td)
    in Td (created by Tr)
    in tr (created by Tr)
    in Tr (created by Table)
    in tbody (created by Table)
    in table (created by Table)
    in Table (created by HorseRacingRunnersTable)
    in HorseRacingRunnersTable (created by HorseRacingRacecard)
    in section (created by HorseRacingRacecard)
    in div (created by HorseRacingRacecard)
    in HorseRacingRacecard (created by Connect(HorseRacingRacecard))
    in Connect(HorseRacingRacecard) (created by Connect(Connect(HorseRacingRacecard)))
    in Connect(Connect(HorseRacingRacecard)) (created by RouterContext)
    in section (created by App)
    in div (created by App)
    in App (created by RouterContext)
    in RouterContext (created by AsyncConnect)
    in AsyncConnect (created by Connect(AsyncConnect))
    in Connect(AsyncConnect)
    in Provider`

**Comment by hassankhan** [comment]
It seems this has been done in a bit of a borked way ... people have updated certain elements at a time. #306 actually seemed like it did a thorough job, but yeah, perhaps time for another PR?

**Comment by vdh** [comment]
@hassankhan #306 only "fixed" the issue because it completely removed the props spread on the `<td>` element.

The issue seems to be caused by [`thead.jsx` creating a value called `props` alongside `key` and `label` in the `column` values](https://github.com/glittershark/reactable/blob/master/src/reactable/thead.jsx#L13), which then [gets incorrectly merged into the props inside `td.jsx`](https://github.com/glittershark/reactable/blob/master/src/reactable/td.jsx#L21).

I would attempt to fix this but I'm confused about the logic behind this column prop sharing code to begin with.

**Comment by vdh** [comment]
Okay, so…

[This is the (venerable) commit that created the inheritance from the `column` prop.](https://github.com/glittershark/reactable/commit/c5ccae39f0c88977f10268b6ebae1295acc76994)
But then [this commit added `column.props` to `thead.jsx` without updating the logic in `td.jsx`](https://github.com/glittershark/reactable/commit/2b97c135841866dec3a8232fd341d24dadf0b022), thus creating this issue.

**Comment by hassankhan** [comment]
Yeah it seemed like something weird had happened, thanks for investigating 👍

**Comment by fijolekProjects** [comment]
I've got:
```
Warning: Unknown props `previousPageLabel`, `nextPageLabel` on <table> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
```
Is this the same issue as above or maybe I should create another issue?

**Comment by Daniel-Baranowski-BJSS** [comment]
@glittershark Are you planning on fixing this issue? Its been 20 days and we didn't get any response from you.

**Comment by vdh** [comment]
@fijolekProjects I have a fix for that pending in PR #314

**Comment by vdh** [comment]
@glittershark You should probably re-open this issue. #314 didn't have a fix for this issue, only the unrelated issues mentioned by others.

I haven't attempted to fix this `props` on `td` issue because I don't know what the original logic behind the code was. I didn't want to break things further trying to bodge something I didn't understand. I've managed to trace the issue back to their original commits and the commit that broke it, but the design purpose of it all is still uncertain to me. I was hoping you would know how to fix this one better than I could.

**Comment by glittershark** [comment]
I'm gonna take a closer look at this once I clear some time (potentially later this week). As I'm sure you've noticed, work has been taking up a lot of my time in the last few months :smile:

**Comment by kinyat** [comment]
The following code will generate the same error

`<Table
                className="hover table-full-width"
                data={[
                    { Name: 'Griffin Smith', Age: 18 },
                    { Age: 23,  Name: 'Lee Salminen' },
                    { Age: 28, Position: 'Developer' },
                ]}
            >
                <Thead>
                    <Th column="Name"/>
                    <Th column="Age" className="fit"/>
                    <Th column="Position" className="fit"/>
                </Thead>
            </Table>`

**Comment by kinyat** [comment]
Will it be a problem to just ignore props when merging props in td?

In reactable/lib/reactable/td.js, line 55, add a check for props
```javascript
if (key !== 'key' && key !== 'name' && key !== 'props') {
    mergedProps[key] = this.props.column[key];
}
```

**Comment by hassankhan** [comment]
IIRC, the recommended way is to have a list of properties for the component, and to remove those properties from the wrapped component. Could be wrong, I think I saw it done that way in `react-bootstrap`.

**Comment by lgraubner** [comment]
Any fix coming soon?

**Comment by hassankhan** [comment]
I believe it has been fixed, but there hasn't been a new release on npm yet.

**Comment by lgraubner** [comment]
Cool, hope to see it on npm soon. 👍

**Comment by vdh** [comment]
@hassankhan @lgraubner No fix yet, someone will have to tackle [the logic conflict between those two commits I highlighted earlier](https://github.com/glittershark/reactable/issues/311#issuecomment-242281315). It looks like @glittershark has a busy schedule so if anyone wants it fixed sooner it would be better to help out with a PR.

**Comment by rizkiandrianto** [comment]
Any update guys?

**Comment by ericf89** [comment]
I think I fixed it with my PR, but I'm not sure if I broke any other intended behavior.  You can try it locally with `"reactable":"git://github.com/ericf89/reactable.git#aab6bcbe05bdf5ac02d5673dbac51cb008bac01a"` in your package.json.

**Comment by marknv** [comment]
Thanks @ericf89, I regression tested your version on my table with customized headers, footers, columns, pagination, sorting, filtering. And doesn't seems to have any problem on those major features.

**Comment by marknv** [comment]
@vdh or @glittershark could you take a look at PR #328, I used @ericf89's version on a table with customized almost everything (thead, tbody, tfoot, pagination, filtering and sorting), and it doesn't seem have any regression to me.

**Comment by cjbrowne** [comment]
@ericf89 works for us, looking forward to this making it into a release :)

**Comment by glittershark** [comment]
Just pushed 0.14.1, can you all confirm that fixes this issue?

**Comment by hassankhan** [comment]
I can confirm, no more warnings 👍

**Comment by glittershark** [comment]
woo! 🎉

**Comment by highwaycoder** [comment]
Confirmed working with 0.14.1, updated package.json this morning :) :tada:
