### ISSUE TITLE
Filtering is not working if the value is placed inside <div>, like this <Td><div>data</div></Td>

### ISSUE THREAD

**Issue by sreevarsh** [glittershark/reactable#318]
Hi,
If the table data is placed inside a div like this <Td><div>some data</div></Td>. the filtering is not working.

Thank you

**Comment by stahlmanDesign** [comment]
I also have this problem. Cannot sort if inside a link tag.

**Comment by stahlmanDesign** [comment]
I solved my problem for sorting. When inside a <div> or <Link> I put a custom sorting function and accessed a.props.children to get the text. ```sortable={[
                {
                  column: this.localisation.Title[this.provider.state.lang],
                  sortFunction: function(a, b){
                    // Sort by last name
                    console.log(a)
                    //var nameA = a.split(' ');
                    //var nameB = b.split(' ');
                    return a.props.children > b.props.children ? 1 : -1;
                    //return nameA[1].localeCompare(nameB[1]);
                  }
                }```

**Comment by glittershark** [comment]
Pass a `value` prop to the `Td`

**Comment by stahlmanDesign** [comment]
Thought I tried that before, but I confirm that it works. Simple. Thanks
