### ISSUE TITLE
Wrapping cell contents inside of <Link> from react-router?

### ISSUE THREAD

**Issue by joeyfigaro** [glittershark/reactable#325]
@glittershark Not entirely sure how to go about doing this. Any way to get some examples on wrapping/manipulating cell content?

**Comment by glittershark** [comment]
see [these docs](https://github.com/glittershark/reactable#even-more-customization)

**Comment by thetmkay** [comment]
Make sure to use `value={foobar}` instead of `data={foobar}` or else it won't work (the docs are wrong).

See #252
