### ISSUE TITLE
Possibility to remove pagination for print

### ISSUE THREAD

**Issue by sassanh** [glittershark/reactable#330]
Thanks for this great module.
Is it possible to remove pagination when printing a reactable? Usually changes in ui for print version are done by media queries (`@meida print { ... }`) but I don't understand how to achieve this for disabling the pagination.

**Comment by brinley** [comment]
This should hide pagination for print media

`@media print
{
    .reactable-pagination {display: none;}
}`

**Comment by sassanh** [comment]
Yeah, thanks.
