### ISSUE TITLE
Mobile-friendly?

### ISSUE THREAD

**Issue by isaachinman** [glittershark/reactable#351]
So I ctrl+f'd for `mobile` and `responsive` in the issues on the project, and found nothing. I have a suspicion the answer to my question is going to be "it depends on your use case", but does this project attempt to be responsive or mobile-friendly in any way? 

To me it seems like the strongest example of React-based html tables with an extremely intuitive API. But (personally), basic responsiveness is a deal-breaker.

**Comment by glittershark** [comment]
All Reactable does is render HTML. If you want to write CSS to make that HTML responsive, that's up to you.

**Comment by isaachinman** [comment]
Fair enough.
