### ISSUE TITLE
Sorting numbers or currency only sorts the first digit

### ISSUE THREAD

**Issue by iweurman** [glittershark/reactable#399]
If i sort my Column it only sorts from the first digits, but not the whole number.
How can I fix this? it doesn't matter if I use the currency sort function or numbers.
The numbers are fetched from objects, do I need to convert those to strings maybe?

Currency:
88
860
810000
756
74500
5240
472200
4651
297100
241700
23390
1...
etc...

```
sortable={{
  column: 'Currency', Currency: function (a, b) {
    return a > b ? 1 : -1;
   }
}}
```

**Comment by shukla2009** [comment]
+1
