### ISSUE TITLE
Row Callbacks 

### ISSUE THREAD

**Issue by jxm262** [glittershark/reactable#63]
Hi, Similar to #5, I think it would be cool to have row callbacks.  My particular use case is to perform some action (highlighted) when a row is selected (clicked).  I also have cases where I need to perform an action (popup a modal, etc... ) when a row is double clicked.

I'll try to look through your source this week and see if I can maybe help.

Thanks!

**Comment by tomask-de** [comment]
@glittershark 
Could you provide an example for that, e.g. a simple hover effect for a row with onMouseOver and onMouseOut?

Thx in advance
