### ISSUE TITLE
Separate code into different files.

### ISSUE THREAD

**Issue by glittershark** [glittershark/reactable#80]
`reactable.jsx` is 833 lines. `reactable_test.jsx` is 2070 lines. It's time to put this shit into different files.

**Comment by yosiat** [comment]
@glittershark I will do it.. I will use browserify to accomplish this.

**Comment by thechrisproject** [comment]
I was just taking a look at this. reactable_tests seems to have a lot of duplication, unless I'm missing something
![screen shot 2015-02-13 at 10 20 21 am](https://cloud.githubusercontent.com/assets/482304/6190782/fdcefe9a-b369-11e4-905a-542b64659acb.png)

**Comment by glittershark** [comment]
@thechrisproject that's... definitely an issue. Going to do a diff of the two and try to consolidate them.
