### ISSUE TITLE
Upgrade to React 0.12

### ISSUE THREAD

**Issue by glittershark** [glittershark/reactable#82]

**Comment by gregeinfrank** [comment]
Any update on when this upgrade will happen?

**Comment by glittershark** [comment]
As soon as someone makes a comment like this asking for it :smile: I should be able to get it done this evening.

**Comment by gregeinfrank** [comment]
Yay! Awesome, looking forward to using it in my react 0.12 app :+1:

**Comment by gregeinfrank** [comment]
thanks!
